using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Sam.Common.Util
{
    public enum RelatorioEnum : byte
    {
        Orgao = 1,
        UO = 2,
        UA = 3,
        Gestor = 4,
        UGE = 5,
        Unidade = 6,
        CentroCusto = 7,
        Classe = 8,
        Responsavel = 9,
        GrupoMaterial = 10,
        Divisao = 11,
        Almoxarifado = 12,
        Material = 13,
        ItemMaterial = 14,
        NaturezaDespesa = 15,
        UnidadeFornecimento = 16,
        SubitensMaterial = 17,
        ContaAuxiliar = 18,
        Fornecedores = 19,
        RelacaoItemSubitem = 20,
        FonteRecurso = 21,
        Sigla = 22,
        PTRes = 23,
        TipoIncorp = 24,
        Terceiro = 25,
        MotivoBaixa = 26,
        EntradaMaterial = 27,
        SaidaMaterial = 28,
        ReservaMaterial = 29,
        RequisicaoMaterial = 30,
        ConsultaEstoqueSintetico = 31,
        ConsultaEstoqueAnalitico = 32,
        ConsultaMovimentacaoEntrada = 33,
        ConsultaMovimentacaoSaida = 34,
        MovimentoItem = 35,
        ConsultaConsumoAlmox = 36,
        ConsultaConsumoRequisitante = 37,
        MensalBalancete = 40,
        MensalBalanceteConsumo = 41,
        MensalBalancetePatrimonio = 42,
        MensalAnalitico = 43,
        MensalAnaliticoConsumo = 44,
        MensalAnaliticoPatrimonio = 45,
        MensalGrupoClasseMaterial = 46,
        MensalInventario = 47,
        GerenciaCatalogo = 48,
        ConsultaPrevisaoConsumoAlmox = 49,
        ConsultaSubitemMaterial = 50,
        ConsultaDivisao = 51,
        BalanceteSimulacao = 52,
        ConsultaSubitemMaterialAlmoxPorND = 53,
        ConsultaEstoqueAnaliticoFichaPrateleira = 54,
        ExportacaoCustos = 55,
        BalanceteAnual = 56,
        ConsultaMovimentacaoTransferencia = 57,
        ConsulmoSubitemAlmox = 58,
        Usuarios = 59,
        UsuariosSemPerfil = 60,
        UnidadeFornecimentoSiafem = 61,
        ConsumoImediato = 62,
        ExportacaoCustosConsumoImediato = 63
    }
}
