DROP TABLE [dbo].[TicketStatus]
GO

--CREATE TABLE [dbo].[TicketStatus](
--	[Id] [int] IDENTITY(1,1) NOT NULL,
--	[Description] [varchar](200) NOT NULL,
-- CONSTRAINT [PK_TicketStatus] PRIMARY KEY CLUSTERED 
--(
--	[Id] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--) ON [PRIMARY]